export const slideData = [
    {
        image: 'https://m.media-amazon.com/images/M/MV5BYTZjNzI1ZTItOTE5Ny00MjBjLWE1NjUtOWRkZWVkOTk2OTZmXkEyXkFqcGdeQXVyOTI3MzI4MzA@._V1_FMjpg_UX1000_.jpg',
        rating: 7.6,
        title: 'Monica, O My Darling',
        year: 2022,
        time: 129,
        videoId: 'AQubo_u_jec',
        date: '11 November',
        origin: 'India',
        language: 'Hindi',
        director: 'Vasan Bala',
        budget: '35',
        watch: 'Netflix',
        desc: 'A young man desperately tries to make it big with some unlikely allies and a dastardly diabolical plan to pull off the perfect murder.',
    },
    {
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0iSjN7F6ZtocIqcBFGFtW1FfvCwTNw9S30uNmhNGiqRYH3J2dw3rv73YY4vCWaDr175c&usqp=CAU',
        rating: 9.0,
        title: 'Kantara',
        year: 2022,
        time: 148,
        videoId: '6oKFao0aISA',
        date: '30 September',
        origin: 'India',
        language: 'Kannada, Hindi',
        director: 'Rishab Shetty',
        budget: '16',
        watch: 'Netflix',
        desc: 'A fiery young man clashes with an unflinching forest officer in a south Indian village where spirituality, fate and folklore rule the lands.',
    },
    {
        image: 'https://m.media-amazon.com/images/M/MV5BZjdjOTQwY2UtZDM5Zi00YTU0LWIzOTQtMTFjZThmZDNhOWZhXkEyXkFqcGdeQXVyMTE0MTY2Mzk2._V1_FMjpg_UX1000_.jpg',
        rating: 6.9,
        title: 'Hit: The First Case',
        year: 2022,
        time: 132,
        videoId: 'JtdCIn47v5g',
        date: '15 July',
        origin: 'India',
        language: 'Hindi',
        director: 'Sailesh Kolanu',
        budget: '6.2',
        watch: 'Netflix',
        desc: 'A brilliant but troubled police inspector sets out to solve a confounding case, all while fighting to gain clarity into his troubled past.',
    },
];

export const MovieTypeData = [
    {
        item: [
            'Other Providers',
            'Prime Video',
            'Prime Video(Rent/Buy)',
            'In Theatres',
        ],
    },
    {
        item: ['Drama', 'Thriller', 'Action', 'More...'],
    },
];

export const TVTypeData = [
    {
        item: ['Other Providers', 'Prime Video'],
    },
    {
        item: ['Drama', 'Thriller', 'Crime', 'More...'],
    },
];

export const TypeData = [
    {
        item: [
            'Other Providers',
            'Prime Video',
            'Prime Video(Rent/Buy)',
            'In Theatres',
        ],
    },
    {
        item: ['Drama', 'Thriller', 'Action', 'More...'],
    },
];

export const movieData = [
    {
        image: 'https://m.media-amazon.com/images/M/MV5BYTZjNzI1ZTItOTE5Ny00MjBjLWE1NjUtOWRkZWVkOTk2OTZmXkEyXkFqcGdeQXVyOTI3MzI4MzA@._V1_FMjpg_UX1000_.jpg',
        rating: 7.6,
        title: 'Monica, O My Darling',
        year: 2022,
        time: 129,
        videoId: 'AQubo_u_jec',
        date: '11 November',
        origin: 'India',
        language: 'Hindi',
        director: 'Vasan Bala',
        budget: '35',
        watch: 'Netflix',
        desc: 'A young man desperately tries to make it big with some unlikely allies and a dastardly diabolical plan to pull off the perfect murder.',
    },
    {
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0iSjN7F6ZtocIqcBFGFtW1FfvCwTNw9S30uNmhNGiqRYH3J2dw3rv73YY4vCWaDr175c&usqp=CAU',
        rating: 9.0,
        title: 'Kantara',
        year: 2022,
        time: 148,
        videoId: '6oKFao0aISA',
        date: '30 September',
        origin: 'India',
        language: 'Kannada, Hindi',
        director: 'Rishab Shetty',
        budget: '16',
        watch: 'Netflix',
        desc: 'A fiery young man clashes with an unflinching forest officer in a south Indian village where spirituality, fate and folklore rule the lands.',
    },
    {
        image: 'https://m.media-amazon.com/images/M/MV5BZmNjNGYxOGEtYjkwMC00YmQyLThjZTYtMThlMmY0MmIzZmRiXkEyXkFqcGdeQXVyMTkzOTcxOTg@._V1_.jpg',
        rating: 7.9,
        title: 'Uunchai',
        year: 2022,
        time: 173,
        videoId: 'nS5xqazKipA',
        date: '11 November',
        origin: 'India',
        language: 'Hindi',
        director: 'Sooraj Barjatya',
        budget: '20',
        watch: 'Netflix',
        desc: 'Three friends leave their cozy lives behind to embark on a journey to Mount Everest.',
    },
    {
        image: 'https://m.media-amazon.com/images/M/MV5BN2RjZDJhYzUtOTQ5Yy00OWM3LWE5OTctM2Y0YWVmNzAzODllXkEyXkFqcGdeQXVyMTA3MDk2NDg2._V1_.jpg',
        rating: 8.5,
        title: 'Sita Rama',
        year: 2022,
        time: 165,
        videoId: '3UKsbXQUwqw',
        date: '5 August',
        origin: 'India',
        language: 'Hindi, Telugu',
        director: 'Hanu Raghavapudi',
        budget: '30',
        watch: 'Netflix',
        desc: "Upon returning to Pakistan, Afreen sets off to fulfil her grandfather's wish of delivering a letter from Ram to Sita. Along the way, she finds Ram and learns about their love story.",
    },
    {
        image: 'https://gutsyindians.com/wp-content/uploads/2022/03/FOw6RHHaQAEJopz-1-1170x1657.jpg',
        rating: 8.0,
        title: 'Rise Roar Revolt',
        year: 2022,
        time: 187,
        videoId: 'GY4BgdUSpbE',
        date: '24 March',
        origin: 'India',
        language: 'Telugu',
        director: 'S. S. Rajamouli',
        budget: '550',
        watch: 'Hotstar',
        desc: 'A fearless revolutionary and an officer in the British force, who once shared a deep bond, decide to join forces and chart out an inspirational path of freedom against the despotic rulers.',
    },
    {
        image: 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSCmwbcVs6Qbwf_vSX04HN4uGW7IwamqXrb8o0HIVWvUbuTTLt2',
        rating: 8.2,
        title: 'Jogi',
        year: 2022,
        time: 80,
        videoId: 'X3VgZVsvt-U',
        date: '16 September',
        origin: 'India',
        language: 'Hindi',
        director: 'Ali Abbas Zafar',
        budget: '15',
        watch: 'Netflix',
        desc: 'Three intrepid friends of different faiths join forces in a noble but dangerous effort to liberate hundreds of people in their city amid rising tensions across India during the 1980s.',
    },
    {
        image: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQEJ6XEfDIp0CAlNbhoICrQjgwfdN14rYu19GVnL3NroFfsimr7',
        rating: 7.9,
        title: 'Chup',
        year: 2022,
        time: 135,
        videoId: 'V51sMMFMWqg',
        date: '23 September',
        origin: 'India',
        language: 'Hindi',
        director: 'R. Balki',
        budget: '10',
        watch: 'ZEE5',
        desc: 'The film centers on Suresh, a lonely movie director who stumbles into Shanti one evening and casts her as the lead in a film. In a twist of fate, Shanti becomes a superstar and Suresh falls from the upper echelons of the film industry.',
    },
    {
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQw2VxIEE0vybIq_UaVr9SFv-906yzKYuuln0SF07dCB3frs2Qj',
        rating: 7.4,
        title: 'VR(Vikrant Rona)',
        year: 2022,
        time: 148,
        videoId: 'VV9SfpGRVFw',
        date: '28 July',
        origin: 'India',
        language: 'Kannada',
        director: 'Anup Bhandari',
        budget: '100',
        watch: 'ZEE5',
        desc: 'When Vikrant Rona sets off to investigate a gruesome murder, a series of tragic deaths leads him to discover a supernatural connection. With varying signals and clues, Vikrant must find the killer.',
    },
    {
        image: 'https://m.media-amazon.com/images/M/MV5BNmNmYjBmYjgtZjlmZC00OWQyLTgzZGQtMGVkNDQ5NDlkZTM2XkEyXkFqcGdeQXVyMTA5MjQ4MDg4._V1_.jpg',
        rating: 8.4,
        title: 'Vikram',
        year: 2022,
        time: 175,
        videoId: 'L4LWIXngIG0',
        date: '3 June',
        origin: 'India',
        language: 'Tamil',
        director: 'Lokesh Kanagaraj',
        budget: '550',
        watch: 'Hotstar',
        desc: 'A special agent investigates a murder committed by a masked group of serial killers. However, a tangled maze of clues soon leads him to the drug kingpin of Chennai.',
    },
    {
        image: 'https://m.media-amazon.com/images/M/MV5BZjdjOTQwY2UtZDM5Zi00YTU0LWIzOTQtMTFjZThmZDNhOWZhXkEyXkFqcGdeQXVyMTE0MTY2Mzk2._V1_FMjpg_UX1000_.jpg',
        rating: 6.9,
        title: 'Hit: The First Case',
        year: 2022,
        time: 132,
        videoId: 'JtdCIn47v5g',
        date: '15 July',
        origin: 'India',
        language: 'Hindi',
        director: 'Sailesh Kolanu',
        budget: '6.2',
        watch: 'Netflix',
        desc: 'A brilliant but troubled police inspector sets out to solve a confounding case, all while fighting to gain clarity into his troubled past.',
    },
    {
        image: 'https://m.media-amazon.com/images/M/MV5BNzJiMTI3ZTMtNTFhYy00OWNhLWExYjItNzU4NmRkNzdmYmJkXkEyXkFqcGdeQXVyMTEzNzg0Mjkx._V1_.jpg',
        rating: 8.0,
        title: 'Vendhu Thanindhathu Kaadu',
        year: 2022,
        time: 177,
        videoId: 'vtJsH5--wkM',
        date: '15 September',
        origin: 'India',
        language: 'Hindi',
        director: 'Gautham Vasudev Menon',
        budget: '30',
        watch: 'Prime Video',
        desc: "A young low-caste village boy travels to Mumbai to earn a living and to study. His quest takes him on a series of unexpected events, where he gets involved in the underground activities of Mumbai's Tamil gangsters.",
    },
];

export const TVData = [
    {
        image: 'https://m.media-amazon.com/images/M/MV5BNDlkNzI2MWUtYTkyOS00MTkxLTg0YzctZmQwNjExYjQzOTc1XkEyXkFqcGdeQXVyMTExMTIzMTA5._V1_.jpg',
        rating: 8.4,
        title: 'College Romance',
        year: 2018,
        time: 40,
        eps: 15,
    },
    {
        image: 'https://m.media-amazon.com/images/M/MV5BYzM5ZjllNDYtMjRlYS00ODkzLWJiNTMtMTEyNzA0OGRjMzAzXkEyXkFqcGdeQXVyMTExMTIzMTA5._V1_.jpg',
        rating: 7.4,
        title: 'Flames',
        year: 2018,
        time: 30,
        eps: 15,
    },
    {
        image: 'https://m.media-amazon.com/images/M/MV5BNDI0YzMwMDktNzc1OS00N2QyLWFlNDMtZWJlODU2MjQ1YThiXkEyXkFqcGdeQXVyMTAyMTE1MDA1._V1_.jpg',
        rating: 8.4,
        title: 'Tanaav',
        year: 2022,
        time: 18,
        eps: 12,
    },
    {
        image: 'https://m.media-amazon.com/images/M/MV5BNTA2YzMyOWUtODAxNC00ZTI4LThiZWItMzMxYjYxOGFmMDUzXkEyXkFqcGdeQXVyMzE4NjMwMjc@._V1_.jpg',
        rating: 7.4,
        title: 'Dahan: Raakan Ka Rahasya',
        year: 2022,
        time: 23,
        eps: 9,
    },
    {
        image: 'https://m.media-amazon.com/images/M/MV5BNWM1OGE2MmItZWUzZi00OGY5LThhMmQtZmJjZmJlYmQ5NTkwXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg',
        rating: 7.3,
        title: 'Jamtara: Sabka Number Ayega',
        year: 2020,
        time: 187,
        eps: 12,
    },
    {
        image: 'https://m.media-amazon.com/images/M/MV5BYjQ2YmE4OWUtNDZhZi00ZGYxLTg4MzYtYWIwMWI1NDQ5ZDNlXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_FMjpg_UX1000_.jpg',
        rating: 8.5,
        title: 'Delhi Crime',
        year: 2019,
        time: 23,
        eps: 12,
    },
    {
        image: 'https://m.media-amazon.com/images/M/MV5BZmVjMDAzZjMtNGNiNS00NzY3LTk2YjUtYjg0ZWVhYzU3N2ZlXkEyXkFqcGdeQXVyMTE3MzIyMDM5._V1_FMjpg_UX1000_.jpg',
        rating: 8.0,
        title: 'Criminal Justice: Adhura',
        year: 2022,
        time: 35,
        eps: 8,
    },
    {
        image: 'https://m.media-amazon.com/images/M/MV5BMWNjOTRhZmYtZGVjYy00OTdhLWI2ODMtMWMxMjgxMDFiYTc0XkEyXkFqcGdeQXVyMTAyMTE1MDA1._V1_.jpg',
        rating: 8.1,
        title: 'Criminal Justice',
        year: 2019,
        time: 20,
        eps: 10,
    },
    {
        image: 'https://m.media-amazon.com/images/M/MV5BNjdmYzBkNTItZTdhNi00MTI5LTlkNjMtNTYxYjczMmZjMjQzXkEyXkFqcGdeQXVyNDY4NjAxNTc@._V1_FMjpg_UX1000_.jpg',
        rating: 9.2,
        title: 'NCR Days',
        year: 2022,
        time: 50,
        eps: 5,
    },
    {
        image: 'https://m.media-amazon.com/images/M/MV5BZjBkZTZjMzQtZDJhMS00MzE3LTg0MDctZjZhZDhhYjFlODZjXkEyXkFqcGdeQXVyOTIxMzQ0NzU@._V1_FMjpg_UX1000_.jpg',
        rating: 7.9,
        title: 'Maharani',
        year: 2021,
        time: 32,
        eps: 20,
    },
    {
        image: 'https://m.media-amazon.com/images/M/MV5BMzRjZWVmMzItNTdmYS00OWEzLTgyOGUtNThiNTU2ZThlYjY0XkEyXkFqcGdeQXVyMTIxMDk2NDE4._V1_FMjpg_UX1000_.jpg',
        rating: 8.7,
        title: 'The Family Man',
        year: 2019,
        time: 25,
        eps: 20,
    },
];

export const comedyData = [
    {
        image: 'https://m.media-amazon.com/images/M/MV5BNTA2YzMyOWUtODAxNC00ZTI4LThiZWItMzMxYjYxOGFmMDUzXkEyXkFqcGdeQXVyMzE4NjMwMjc@._V1_.jpg',
        rating: 7.4,
        title: 'Dahan: Raakan Ka Rahasya',
        year: 2022,
        time: 23,
        eps: 9,
    },
    {
        image: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQEJ6XEfDIp0CAlNbhoICrQjgwfdN14rYu19GVnL3NroFfsimr7',
        rating: 8.5,
        title: 'Chup',
        year: 2022,
        time: 135,
    },
    {
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQw2VxIEE0vybIq_UaVr9SFv-906yzKYuuln0SF07dCB3frs2Qj',
        rating: 7.4,
        title: 'VR(Vikrant Rona)',
        year: 2022,
        time: 148,
    },
    {
        image: 'https://m.media-amazon.com/images/M/MV5BNmNmYjBmYjgtZjlmZC00OWQyLTgzZGQtMGVkNDQ5NDlkZTM2XkEyXkFqcGdeQXVyMTA5MjQ4MDg4._V1_.jpg',
        rating: 8.4,
        title: 'Vikram',
        year: 2022,
        time: 175,
    },
    {
        image: 'https://m.media-amazon.com/images/M/MV5BZjdjOTQwY2UtZDM5Zi00YTU0LWIzOTQtMTFjZThmZDNhOWZhXkEyXkFqcGdeQXVyMTE0MTY2Mzk2._V1_FMjpg_UX1000_.jpg',
        rating: 6.9,
        title: 'Hit: The First Case',
        year: 2022,
        time: 132,
    },
    {
        image: 'https://m.media-amazon.com/images/M/MV5BZmVjMDAzZjMtNGNiNS00NzY3LTk2YjUtYjg0ZWVhYzU3N2ZlXkEyXkFqcGdeQXVyMTE3MzIyMDM5._V1_FMjpg_UX1000_.jpg',
        rating: 8.0,
        title: 'Criminal Justice: Adhura',
        year: 2022,
        time: 35,
        eps: 8,
    },
    {
        image: 'https://m.media-amazon.com/images/M/MV5BZjBkZTZjMzQtZDJhMS00MzE3LTg0MDctZjZhZDhhYjFlODZjXkEyXkFqcGdeQXVyOTIxMzQ0NzU@._V1_FMjpg_UX1000_.jpg',
        rating: 7.9,
        title: 'Maharani',
        year: 2021,
        time: 32,
        eps: 20,
    },
    {
        image: 'https://m.media-amazon.com/images/M/MV5BMzRjZWVmMzItNTdmYS00OWEzLTgyOGUtNThiNTU2ZThlYjY0XkEyXkFqcGdeQXVyMTIxMDk2NDE4._V1_FMjpg_UX1000_.jpg',
        rating: 8.7,
        title: 'The Family Man',
        year: 2019,
        time: 25,
        eps: 20,
    },
];

export const fanFavorites = [
    {
        image: 'https://m.media-amazon.com/images/M/MV5BYTRiNDQwYzAtMzVlZS00NTI5LWJjYjUtMzkwNTUzMWMxZTllXkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_.jpg',
        rating: 9.2,
        title: 'Game of Thrones',
        year: '2011 - 2019',
        time: 42,
        eps: 73,
    },
    {
        image: 'https://m.media-amazon.com/images/M/MV5BYTdiOTIyZTQtNmQ1OS00NjZlLWIyMTgtYzk5Y2M3ZDVmMDk1XkEyXkFqcGdeQXVyMTAzMDg4NzU0._V1_FMjpg_UX1000_.jpg',
        rating: 8.1,
        title: 'Everything Everywhere All Action',
        year: 2022,
        time: 139,
        type: 'R',
    },
    {
        image: 'https://m.media-amazon.com/images/M/MV5BMDBlMDYxMDktOTUxMS00MjcxLWE2YjQtNjNhMjNmN2Y3ZDA1XkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_.jpg',
        rating: 7.2,
        title: 'Prey',
        year: 2022,
        time: 99,
        type: 'R',
    },
    {
        image: 'https://m.media-amazon.com/images/M/MV5BN2RjZDJhYzUtOTQ5Yy00OWM3LWE5OTctM2Y0YWVmNzAzODllXkEyXkFqcGdeQXVyMTA3MDk2NDg2._V1_.jpg',
        rating: 8.5,
        title: 'Sita Rama',
        year: 2022,
        time: 165,
    },
    {
        image: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQEJ6XEfDIp0CAlNbhoICrQjgwfdN14rYu19GVnL3NroFfsimr7',
        rating: 8.5,
        title: 'Chup',
        year: 2022,
        time: 135,
    },
    {
        image: 'https://m.media-amazon.com/images/M/MV5BNjA3NGExZDktNDlhZC00NjYyLTgwNmUtZWUzMDYwMTZjZWUyXkEyXkFqcGdeQXVyMTU1MDM3NDk0._V1_FMjpg_UX1000_.jpg',
        rating: 7.8,
        title: 'Avatar',
        year: 2009,
        time: 160,
        type: 'PG -13',
    },
    {
        image: 'https://m.media-amazon.com/images/M/MV5BMDZkYmVhNjMtNWU4MC00MDQxLWE3MjYtZGMzZWI1ZjhlOWJmXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg',
        rating: 8.7,
        title: 'Stranger Things',
        year: 2016,
        time: 55,
        eps: 42,
        type: 'R',
    },
    {
        image: 'https://m.media-amazon.com/images/M/MV5BMDdmMTBiNTYtMDIzNi00NGVlLWIzMDYtZTk3MTQ3NGQxZGEwXkEyXkFqcGdeQXVyMzMwOTU5MDk@._V1_.jpg',
        rating: 7.9,
        title: 'The Batman',
        year: 2022,
        time: 172,
        type: 'PG - 13',
    },
];

export const topNews = [
    {
        image: 'https://m.media-amazon.com/images/M/MV5BODJkNDY0MDgtYzFmYy00YzMyLThiNGUtOGI3ZjcyNjk0MWFiXkEyXkFqcGdeQXVyODc0OTEyNDU@._V1_.jpg',
        title: '‘Smile’ Scores 19 Million at Box Office While ‘Bros’ Is a Bust With 4.7 Million',
        description:
            'The box office’s two newest entrants are having very different results, as Paramount’s “Smile” is having a good start in the No. 1 spot while Universal’s “Bros” is looking like the latest theatrical flop.',
        time: '01 October 2022',
        by: 'The Wrap',
    },
    {
        image: 'https://m.media-amazon.com/images/M/MV5BZWYzOGEwNTgtNWU3NS00ZTQ0LWJkODUtMmVhMjIwMjA1ZmQwXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_.jpg',
        title: 'Box Office: ‘Top Gun: Maverick’ Passes ‘Frozen II’ As ‘Minions 2’ Tops $900 Million',
        description:
            'In holdover box office news for the weekend, Sony’s Bullet Train earned $3.25 million (-44%) for a new $92.55 million 38-day domestic total. That’s not bad for David Leitch’s $90 million, R-rated, Brad Pitt-and-friends action comedy that is a ‘new to you’ adaptation for most moviegoers. It should still crawl to $100 million domestic and has already passed $200 million worldwide. It may top out at 2.5x the budget globally, but I expect healthy post-theatrical business and a lot of folks discovering it in seven months on Netflix. It’s not a barn-burner, but A) not every big movie needs to spawn a franchise and B) it’s still a strong enough performance, like Sandra Bullock and Channing Tatum’s The Lost City, to convince Hollywood to still make old-school movies amid the franchise plays.',
        time: 'Sep 11, 2022',
        by: 'HOLLYWOOD & ENTERTAINMENT',
    },
];

export const bornToDay = [
    {
        image: 'https://m.media-amazon.com/images/M/MV5BMzU0NTc3OTExOF5BMl5BanBnXkFtZTcwMjM0MjcxNQ@@._V1_.jpg',
        name: 'Lorraine Bracco',
        age: '2 October 1954',
    },
    {
        image: 'https://m.media-amazon.com/images/M/MV5BMjA1NTUxMTk3N15BMl5BanBnXkFtZTcwNjg3MDM3Nw@@._V1_.jpg',
        name: 'Camilla Belle',
        age: '2 October 1987',
    },
    {
        image: 'https://m.media-amazon.com/images/M/MV5BZTY3NTE5N2QtNWVmYy00ZWFjLTgzZTMtOTY2ZjM4MGY2OTRmXkEyXkFqcGdeQXVyNTI5Mjg0Mg@@._V1_.jpg',
        name: 'Brianna Brown',
        age: '2 October 1979',
    },
    {
        image: 'https://hips.hearstapps.com/hmg-prod/images/joseph-baena-is-seen-on-july-04-2019-in-los-angeles-news-photo-1570553570.jpg',
        name: 'Joseph Baena',
        age: '2 October 1997',
    },
    {
        image: 'https://m.media-amazon.com/images/M/MV5BODgzMzM2NTE0Ml5BMl5BanBnXkFtZTcwMTcyMTkyOQ@@._V1_UY1200_CR76,0,630,1200_AL_.jpg',
        name: 'Kate Winslet',
        age: '5 October 1975',
    },
    {
        image: 'https://i.guim.co.uk/img/media/d0d983846ba253cc749ecf17ac23b302790d4149/14_88_2442_1465/master/2442.jpg?width=1200&height=1200&quality=85&auto=format&fit=crop&s=9536a5786b0e0cabc18b8690e6703ab4',
        name: 'Emilia Clarke',
        age: '3 October 1986',
    },
    {
        image: 'https://m.media-amazon.com/images/M/MV5BODUwODZlMWQtY2Y0Ni00Yjg1LThlOGMtNmE3NzNjNWFiZjg1XkEyXkFqcGdeQXVyNDY3MjI1Mjg@._V1_.jpg',
        name: 'Thea Sofie Loch Naess',
        age: '26 November 1996',
    },
    {
        image: 'https://m.media-amazon.com/images/M/MV5BYTE4YmYzOTItM2EzNy00ZWI3LWJkZDEtNmMyOTQ3M2JiNTk2XkEyXkFqcGdeQXVyMTc2Mzc3NzA@._V1_UX178_CR0,0,178,264_AL_.jpg',
        name: 'Aubrey Peeples',
        age: '26 November 1993',
    },
    {
        image: 'https://m.media-amazon.com/images/M/MV5BMTZiZmUzZTgtMWQ3Yy00MjY4LTk2NWMtMmNjMzA2YTIxYTA4XkEyXkFqcGdeQXVyNzEwNjQwMTY@._V1_.jpg',
        name: 'Peter Facinelli',
        age: '26 November 1973',
    },
    {
        image: 'https://m.media-amazon.com/images/M/MV5BMjIzOTI4MDAzNV5BMl5BanBnXkFtZTcwNDk4MzYxNw@@._V1_UY1200_CR107,0,630,1200_AL_.jpg',
        name: 'Tamsin Egerton',
        age: '26 November 1988',
    },
];

export const TopBox = [
    {
        title: "Don't Worry Darling",
        price: '19.3M',
    },
    {
        title: 'The Women King',
        price: '11M',
    },
    {
        title: 'Avatar',
        price: '10.5M',
    },
    {
        title: 'Barbarian',
        price: '4.8M',
    },
    {
        title: 'See How They Run',
        price: '1.9M',
    },
    {
        title: 'Pearl',
        price: '1.8M',
    },
];
